import React from 'react';
import {AbsoluteFill, Audio, interpolate, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {TIMELINE} from './generatedTimeline';

const C={bg:'#07130f',bg2:'#0a1a15',panel:'#10241d',text:'#f7faf8',accent:'#55e69f',accent2:'#b8ffda',muted:'#9cb5aa',line:'#24483a'};
const font='Noto Sans Arabic, Noto Kufi Arabic, Arial, sans-serif';

const Brand=()=> <div style={{position:'absolute',top:72,right:70,fontFamily:font,color:C.accent,fontSize:27,fontWeight:800,direction:'rtl'}}>خلف الرقم</div>;
const Grid=()=> <AbsoluteFill style={{opacity:.14,backgroundImage:`linear-gradient(${C.line} 1px,transparent 1px),linear-gradient(90deg,${C.line} 1px,transparent 1px)`,backgroundSize:'90px 90px'}}/>;
const Caption:React.FC<{children:React.ReactNode}>=({children})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:18}});return <div style={{position:'absolute',left:80,right:80,bottom:180,textAlign:'center',fontFamily:font,fontSize:42,lineHeight:1.5,fontWeight:800,color:C.text,direction:'rtl',opacity:p,transform:`translateY(${interpolate(p,[0,1],[28,0])}px)`}}>{children}</div>};
const Scene:React.FC<{index:number;children:React.ReactNode}>=({index,children})=><AbsoluteFill style={{background:`radial-gradient(circle at 50% 18%,${C.bg2},${C.bg} 64%)`,color:C.text,overflow:'hidden'}}><Grid/><Brand/>{children}<Audio src={staticFile(`audio/scene_${String(index).padStart(2,'0')}.mp3`)}/></AbsoluteFill>;

const NumberHero=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:14,stiffness:105}});const value=Math.round(interpolate(p,[0,1],[68,467]));return <Scene index={1}><div style={{position:'absolute',top:330,left:0,right:0,textAlign:'center',fontFamily:font,color:C.muted,fontSize:35,direction:'rtl'}}>قدرة مراكز البيانات في السعودية</div><div style={{position:'absolute',top:500,left:0,right:0,textAlign:'center'}}><span style={{fontSize:230,fontWeight:950}}>{value}</span><span style={{fontSize:72,color:C.accent,fontWeight:900,marginLeft:20}}>MW</span></div><div style={{position:'absolute',top:850,left:165,width:750,height:18,borderRadius:20,background:C.panel,overflow:'hidden'}}><div style={{height:'100%',width:`${p*100}%`,background:`linear-gradient(90deg,${C.accent},${C.accent2})`}}/></div><Caption>من 68 إلى 467 ميغاواط… لماذا هذا الرقم مهم؟</Caption></Scene>};
const Servers=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();return <Scene index={2}><div style={{position:'absolute',top:290,left:120,right:120,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:18}}>{Array.from({length:16}).map((_,i)=>{const p=spring({frame:f-i*2,fps,config:{damping:16}});return <div key={i} style={{height:125,borderRadius:22,background:C.panel,border:`1px solid ${C.line}`,opacity:p,transform:`translateY(${(1-p)*30}px)`}}><div style={{width:13,height:13,borderRadius:10,background:i%3===0?C.accent:C.muted,margin:'22px 0 0 22px'}}/><div style={{height:7,margin:'25px 20px 0',background:C.line,borderRadius:8}}/><div style={{height:7,margin:'10px 20px 0',background:C.line,borderRadius:8}}/></div>})}</div><div style={{position:'absolute',top:790,left:0,right:0,textAlign:'center',fontFamily:font,fontSize:62,fontWeight:950,direction:'rtl'}}>آلاف الخوادم تعمل بلا توقف</div><Caption>الذكاء الاصطناعي لا يعيش في التطبيق فقط. خلفه آلاف الخوادم تعمل بلا توقف.</Caption></Scene>};
const Factory=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:16}});return <Scene index={3}><div style={{position:'absolute',top:360,left:110,right:110,display:'flex',alignItems:'center',justifyContent:'space-between'}}><div style={{width:330,height:330,borderRadius:52,background:C.panel,display:'flex',alignItems:'center',justifyContent:'center',fontFamily:font,fontSize:46,direction:'rtl',color:C.muted}}>تخزين</div><div style={{fontSize:85,color:C.accent}}>→</div><div style={{width:390,height:390,borderRadius:62,background:C.accent,color:C.bg,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',fontFamily:font,fontWeight:950,fontSize:52,direction:'rtl',transform:`scale(${.86+p*.14})`}}>مصنع<br/>حوسبة</div></div><Caption>مركز البيانات يتحول من مخزن للملفات إلى مصنع حوسبة للذكاء الاصطناعي.</Caption></Scene>};
const Flow=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const items=['AI','GPU','POWER','COOLING','FIBER'];return <Scene index={4}><div style={{position:'absolute',top:385,left:65,right:65}}><div style={{fontFamily:font,fontSize:35,color:C.muted,textAlign:'center',marginBottom:75,direction:'rtl'}}>ما الذي يشغّل الذكاء الاصطناعي؟</div><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:10}}>{items.map((x,i)=>{const p=spring({frame:f-i*8,fps,config:{damping:14}});return <React.Fragment key={x}><div style={{width:165,height:165,borderRadius:34,background:i===0?C.accent:C.panel,color:i===0?C.bg:C.text,display:'flex',alignItems:'center',justifyContent:'center',fontSize:x.length>5?23:33,fontWeight:950,transform:`scale(${p})`,opacity:p,border:`1px solid ${i===0?C.accent:C.line}`}}>{x}</div>{i<items.length-1&&<div style={{fontSize:40,color:C.accent}}>→</div>}</React.Fragment>})}</div></div><Caption>وهذا يرفع الطلب على الرقائق والكهرباء والتبريد والألياف الضوئية.</Caption></Scene>};
const Investment=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:15}});const v=interpolate(p,[0,1],[0,16]);return <Scene index={5}><div style={{position:'absolute',top:360,left:0,right:0,textAlign:'center',fontFamily:font,color:C.muted,fontSize:36,direction:'rtl'}}>استثمارات مراكز البيانات منذ 2016</div><div style={{position:'absolute',top:520,left:0,right:0,textAlign:'center'}}><span style={{fontSize:220,fontWeight:950}}>{v.toFixed(1)}</span><div style={{fontFamily:font,fontSize:72,color:C.accent,fontWeight:900,direction:'rtl'}}>مليار ريال+</div></div><Caption>ومنذ 2016 تجاوزت استثمارات مراكز البيانات في المملكة 16 مليار ريال.</Caption></Scene>};
const Race=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:16}});return <Scene index={6}><div style={{position:'absolute',top:350,left:140,right:140}}>{[['التطبيقات',.45],['قدرة الحوسبة',1]].map(([label,max],i)=><div key={String(label)} style={{marginBottom:90}}><div style={{fontFamily:font,fontSize:43,fontWeight:800,direction:'rtl',marginBottom:18}}>{label}</div><div style={{height:92,background:C.panel,borderRadius:24,overflow:'hidden'}}><div style={{height:'100%',width:`${p*Number(max)*100}%`,background:i===1?C.accent:C.line,borderRadius:24}}/></div></div>)}</div><Caption>لذلك السباق القادم ليس على التطبيقات فقط، بل على من يملك قدرة الحوسبة التي تشغلها.</Caption></Scene>};
const Hub=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const nodes=[[190,120],[390,80],[580,190],[320,340],[550,420],[160,450]];return <Scene index={7}><div style={{position:'absolute',top:300,left:0,right:0,textAlign:'center',fontFamily:font,fontSize:36,color:C.muted,direction:'rtl'}}>شبكة حوسبة إقليمية</div><div style={{position:'absolute',top:420,left:130,width:820,height:650,borderRadius:'45% 55% 50% 50%',background:`linear-gradient(145deg,${C.panel},#15362a)`,border:`2px solid ${C.line}`}}>{nodes.map(([x,y],i)=>{const p=spring({frame:f-i*6,fps,config:{damping:13}});return <div key={i} style={{position:'absolute',left:x,top:y,width:34,height:34,borderRadius:30,background:C.accent,transform:`scale(${p})`,boxShadow:`0 0 ${35*p}px ${C.accent}`}}/>})}<div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',fontSize:80,fontWeight:950,color:C.accent}}>KSA</div></div><Caption>إذا استمر النمو، قد تصبح السعودية عقدة رئيسية للحوسبة والذكاء الاصطناعي في المنطقة.</Caption></Scene>};
const End=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:16}});return <Scene index={8}><div style={{position:'absolute',top:470,left:95,right:95,textAlign:'center',fontFamily:font,direction:'rtl',transform:`scale(${.92+p*.08})`}}><div style={{fontSize:34,color:C.accent,fontWeight:900,marginBottom:55}}>خلف الرقم</div><div style={{fontSize:78,fontWeight:950,lineHeight:1.38}}>هل تصبح الحوسبة أصلًا استراتيجيًا مثل الطاقة؟</div></div><Caption>فهل تصبح الحوسبة أصلًا استراتيجياً مثل الطاقة؟</Caption></Scene>};

const visuals=[NumberHero,Servers,Factory,Flow,Investment,Race,Hub,End];

export const BehindTheNumber:React.FC=()=> <AbsoluteFill style={{background:C.bg}}>{TIMELINE.map((t,i)=>{const Comp=visuals[i];return <Sequence key={t.index} from={t.from} durationInFrames={t.frames}><Comp/></Sequence>})}</AbsoluteFill>;
