import React from 'react';
import {AbsoluteFill, Audio, interpolate, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {TIMELINE} from './generatedTimeline';
import {APPROVED_PRESENTER_HERO} from './presenterAsset';

export const NEW_VISUAL_PIPELINE_V3 = true;

const C={bg:'#040817',navy:'#07152b',panel:'rgba(8,22,45,.78)',text:'#f8fbff',cyan:'#35c9ff',gold:'#f4c95d',muted:'#b9c7db',line:'rgba(91,177,255,.28)'};
const font='Noto Sans Arabic, Noto Kufi Arabic, Arial, sans-serif';
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
type P={duration:number};
type Focus='full'|'presenter'|'chart';

const focusPos:Record<Focus,string>={full:'center center',presenter:'24% center',chart:'78% center'};

const Brand=()=> <div style={{position:'absolute',top:40,right:42,zIndex:60,display:'flex',alignItems:'center',gap:12}}><img src={staticFile('brand-logo.svg')} style={{width:104,height:104,objectFit:'contain',filter:'drop-shadow(0 8px 24px rgba(0,0,0,.55))'}}/></div>;

const CinematicBackdrop:React.FC<{focus?:Focus}>=({focus='full'})=>{const f=useCurrentFrame();const x=Math.sin(f/43)*18;const y=Math.cos(f/57)*12;return <>
  <AbsoluteFill style={{background:C.bg}}/>
  <img src={APPROVED_PRESENTER_HERO} style={{position:'absolute',inset:-90,width:'calc(100% + 180px)',height:'calc(100% + 180px)',objectFit:'cover',objectPosition:focusPos[focus],transform:`translate3d(${x}px,${y}px,0) scale(1.22)`,filter:'blur(34px) brightness(.34) saturate(1.25)'}}/>
  <AbsoluteFill style={{background:'radial-gradient(circle at 50% 28%,rgba(53,201,255,.12),transparent 42%),linear-gradient(180deg,rgba(3,7,18,.08),rgba(3,7,18,.58) 62%,rgba(3,7,18,.96))'}}/>
  <AbsoluteFill style={{opacity:.13,backgroundImage:'linear-gradient(rgba(71,159,255,.28) 1px,transparent 1px),linear-gradient(90deg,rgba(71,159,255,.22) 1px,transparent 1px)',backgroundSize:'88px 88px',transform:`translateY(${f%88}px)`}}/>
</>};

const PhotoPanel:React.FC<{focus?:Focus;top?:number;height?:number;contain?:boolean}>=({focus='full',top=155,height=720,contain=false})=>{const f=useCurrentFrame();const z=1.02+Math.sin(f/45)*.015;const shift=Math.sin(f/38)*9;return <div style={{position:'absolute',left:44,right:44,top,height,borderRadius:42,overflow:'hidden',border:'1px solid rgba(87,196,255,.34)',background:'#061020',boxShadow:'0 28px 90px rgba(0,0,0,.55),0 0 55px rgba(53,201,255,.10)',zIndex:12}}>
  <img src={APPROVED_PRESENTER_HERO} style={{width:'100%',height:'100%',objectFit:contain?'contain':'cover',objectPosition:focusPos[focus],transform:`translateX(${shift}px) scale(${z})`,filter:'saturate(1.08) contrast(1.03)'}}/>
  <div style={{position:'absolute',inset:0,boxShadow:'inset 0 -130px 100px rgba(3,7,18,.42)'}}/>
</div>};

const SceneShell:React.FC<{duration:number;focus?:Focus;children:React.ReactNode}>=({duration,focus='full',children})=>{const f=useCurrentFrame();const enter=interpolate(f,[0,10],[0,1],clamp);const exit=interpolate(f,[Math.max(0,duration-10),duration],[1,0],clamp);const scale=interpolate(f,[0,duration],[1.015,1.035],clamp);return <AbsoluteFill style={{overflow:'hidden',opacity:Math.min(enter,exit),transform:`scale(${scale})`,color:C.text}}><CinematicBackdrop focus={focus}/><Brand/>{children}</AbsoluteFill>};

const Glass:React.FC<{children:React.ReactNode;style?:React.CSSProperties}>=({children,style})=><div style={{background:C.panel,border:`1px solid ${C.line}`,backdropFilter:'blur(14px)',boxShadow:'0 18px 60px rgba(0,0,0,.36)',borderRadius:28,...style}}>{children}</div>;

const Caption:React.FC<{text:string}>=({text})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame:f-5,fps,config:{damping:20,stiffness:120}});return <Glass style={{position:'absolute',left:54,right:54,bottom:82,zIndex:50,padding:'22px 30px',opacity:p,transform:`translateY(${(1-p)*28}px)`}}><div style={{fontFamily:font,fontSize:38,lineHeight:1.48,fontWeight:800,textAlign:'center',direction:'rtl',textShadow:'0 4px 18px rgba(0,0,0,.85)'}}>{text}</div><div style={{height:4,width:`${p*150}px`,borderRadius:10,background:`linear-gradient(90deg,${C.cyan},${C.gold})`,margin:'16px auto 0'}}/></Glass>};

const Kicker:React.FC<{children:React.ReactNode}>=({children})=><div style={{position:'absolute',left:62,top:62,zIndex:55,fontFamily:font,fontSize:25,fontWeight:800,color:C.gold,direction:'rtl',letterSpacing:.2}}>{children}</div>;

const Hero:React.FC<P>=({duration})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame:f-7,fps,config:{damping:16,stiffness:105}});return <SceneShell duration={duration} focus="full"><Kicker>القصة خلف الرقم</Kicker><PhotoPanel focus="full" contain top={150} height={730}/><Glass style={{position:'absolute',left:90,right:90,top:930,zIndex:25,padding:'32px 34px',textAlign:'center',transform:`translateY(${(1-p)*45}px)`,opacity:p}}><div style={{fontFamily:font,fontSize:31,color:C.muted,direction:'rtl'}}>قدرة مراكز البيانات في السعودية</div><div style={{display:'flex',alignItems:'baseline',justifyContent:'center',gap:18,marginTop:10}}><b style={{fontSize:104,color:C.text}}>68</b><span style={{fontSize:56,color:C.gold}}>→</span><b style={{fontSize:132,color:C.cyan}}>467</b><span style={{fontSize:38,fontWeight:900,color:C.cyan}}>MW</span></div></Glass><Caption text="السعودية رفعت قدرة مراكز البيانات من 68 إلى 467 ميغاواط. لماذا هذا الرقم مهم؟"/></SceneShell>};

const Compute:React.FC<P>=({duration})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();return <SceneShell duration={duration} focus="presenter"><Kicker>خلف شاشة الـ AI</Kicker><PhotoPanel focus="presenter" top={150} height={820}/><div style={{position:'absolute',left:70,right:70,top:1015,zIndex:30,display:'flex',gap:14,justifyContent:'center'}}>{['AI','GPU','SERVERS'].map((x,i)=>{const p=spring({frame:f-5-i*5,fps,config:{damping:16}});return <Glass key={x} style={{padding:'18px 24px',minWidth:190,textAlign:'center',transform:`translateY(${(1-p)*34}px)`,opacity:p}}><b style={{fontSize:31,color:i===0?C.gold:C.cyan}}>{x}</b></Glass>})}</div><Caption text="الذكاء الاصطناعي لا يعيش في التطبيق فقط. خلفه آلاف الخوادم تعمل بلا توقف."/></SceneShell>};

const Factory:React.FC<P>=({duration})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame:f-5,fps,config:{damping:14,stiffness:105}});return <SceneShell duration={duration} focus="chart"><Kicker>من التخزين إلى الإنتاج</Kicker><PhotoPanel focus="chart" top={155} height={790}/><Glass style={{position:'absolute',left:95,right:95,top:1000,zIndex:25,padding:'30px',textAlign:'center',transform:`scale(${.92+p*.08})`,opacity:p}}><div style={{fontSize:29,color:C.muted,fontFamily:font,direction:'rtl'}}>مركز البيانات يتحول إلى</div><div style={{fontSize:76,fontWeight:950,color:C.gold,marginTop:8}}>AI FACTORY</div><div style={{fontFamily:font,fontSize:30,color:C.cyan,direction:'rtl'}}>مصنع حوسبة</div></Glass><Caption text="ومركز البيانات يتحول من مخزن للملفات إلى مصنع حوسبة للذكاء الاصطناعي."/></SceneShell>};

const Chain:React.FC<P>=({duration})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const items=[['GPU','رقائق'],['POWER','طاقة'],['COOL','تبريد'],['FIBER','ألياف']];return <SceneShell duration={duration} focus="presenter"><Kicker>سلسلة كاملة تعمل خلف السؤال</Kicker><PhotoPanel focus="presenter" top={145} height={640}/><div style={{position:'absolute',left:70,right:70,top:835,zIndex:25,display:'grid',gridTemplateColumns:'1fr 1fr',gap:18}}>{items.map(([en,ar],i)=>{const p=spring({frame:f-4-i*5,fps,config:{damping:16}});return <Glass key={en} style={{padding:'24px 22px',opacity:p,transform:`translateY(${(1-p)*42}px)`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><b style={{fontSize:28,color:i%2?C.gold:C.cyan}}>{en}</b><span style={{fontFamily:font,fontSize:27,fontWeight:800,direction:'rtl'}}>{ar}</span></Glass>})}</div><Caption text="وهذا يرفع الطلب على الرقائق والكهرباء والتبريد والألياف الضوئية."/></SceneShell>};

const Investment:React.FC<P>=({duration})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame:f-5,fps,config:{damping:13,stiffness:100}});const v=interpolate(p,[0,1],[0,16],clamp);return <SceneShell duration={duration} focus="chart"><Kicker>من البنية إلى المال</Kicker><PhotoPanel focus="chart" top={145} height={820}/><Glass style={{position:'absolute',left:115,right:115,top:1010,zIndex:30,padding:'28px 20px',textAlign:'center',opacity:p,transform:`translateY(${(1-p)*40}px)`}}><div style={{fontSize:116,fontWeight:950,color:C.gold,lineHeight:1}}>{v.toFixed(1)}</div><div style={{fontFamily:font,fontSize:48,fontWeight:900,direction:'rtl',color:C.text}}>مليار ريال+</div><div style={{fontFamily:font,fontSize:25,color:C.muted,direction:'rtl',marginTop:8}}>استثمارات منذ 2016</div></Glass><Caption text="ومنذ 2016 تجاوزت استثمارات مراكز البيانات في المملكة 16 مليار ريال."/></SceneShell>};

const Race:React.FC<P>=({duration})=>{const f=useCurrentFrame();const p=interpolate(f,[5,Math.max(30,duration-12)],[0,1],clamp);return <SceneShell duration={duration} focus="presenter"><Kicker>من يملك القدرة؟</Kicker><PhotoPanel focus="presenter" top={145} height={650}/><Glass style={{position:'absolute',left:78,right:78,top:840,zIndex:28,padding:'34px'}}><div style={{fontFamily:font,fontSize:30,direction:'rtl',color:C.muted}}>التطبيقات</div><div style={{height:18,borderRadius:20,background:'rgba(255,255,255,.10)',margin:'14px 0 35px',overflow:'hidden'}}><div style={{height:'100%',width:`${p*38}%`,background:C.muted}}/></div><div style={{fontFamily:font,fontSize:42,direction:'rtl',fontWeight:950,color:C.cyan}}>قدرة الحوسبة</div><div style={{height:28,borderRadius:20,background:'rgba(255,255,255,.10)',marginTop:15,overflow:'hidden'}}><div style={{height:'100%',width:`${p*100}%`,background:`linear-gradient(90deg,${C.cyan},${C.gold})`,boxShadow:`0 0 25px ${C.cyan}`}}/></div><div style={{fontSize:32,fontWeight:900,letterSpacing:4,textAlign:'center',marginTop:26,color:C.gold}}>COMPUTE IS THE MOAT</div></Glass><Caption text="لذلك السباق القادم ليس على التطبيقات فقط، بل على من يملك قدرة الحوسبة التي تشغلها."/></SceneShell>};

const Hub:React.FC<P>=({duration})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const nodes=[[160,1050],[820,1010],[130,1220],[865,1215],[500,1090],[500,1290]];return <SceneShell duration={duration} focus="full"><Kicker>من سوق محلي إلى عقدة إقليمية</Kicker><PhotoPanel focus="full" contain top={145} height={720}/><div style={{position:'absolute',left:0,right:0,top:920,height:430,zIndex:26}}>{nodes.map(([x,y],i)=>{const p=spring({frame:f-i*4,fps,config:{damping:14}});return <span key={i} style={{position:'absolute',left:x,top:y-920,width:20,height:20,borderRadius:20,background:i%2?C.gold:C.cyan,boxShadow:`0 0 30px ${i%2?C.gold:C.cyan}`,transform:`scale(${p})`}}/>})}<Glass style={{position:'absolute',left:250,right:250,top:95,padding:'25px',textAlign:'center'}}><div style={{fontSize:62,fontWeight:950,color:C.cyan}}>SAUDI</div><div style={{fontSize:50,fontWeight:950,color:C.gold}}>AI HUB?</div></Glass></div><Caption text="إذا استمر النمو، قد تصبح السعودية عقدة رئيسية للحوسبة والذكاء الاصطناعي في المنطقة."/></SceneShell>};

const End:React.FC<P>=({duration})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame:f-4,fps,config:{damping:16}});return <SceneShell duration={duration} focus="presenter"><PhotoPanel focus="presenter" top={120} height={880}/><Glass style={{position:'absolute',left:78,right:78,top:1050,zIndex:30,padding:'38px 30px',textAlign:'center',opacity:p,transform:`translateY(${(1-p)*45}px)`}}><img src={staticFile('brand-logo.svg')} style={{width:140,height:140,objectFit:'contain',margin:'0 auto 10px'}}/><div style={{fontFamily:font,fontSize:58,fontWeight:950,direction:'rtl'}}>خلف الرقم</div><div style={{fontFamily:font,fontSize:32,color:C.gold,fontWeight:900,direction:'rtl',marginTop:12}}>الأرقام تحكي… ونحن نكشف ما خلفها</div></Glass><Caption text="فهل تصبح الحوسبة أصلًا استراتيجياً مثل الطاقة؟"/></SceneShell>};

const visuals=[Hero,Compute,Factory,Chain,Investment,Race,Hub,End];
export const BehindTheNumber:React.FC=()=> <AbsoluteFill style={{background:C.bg}}><Audio src={staticFile('audio/master_narration.mp3')}/>{TIMELINE.map((t,i)=>{const Comp=visuals[i] ?? End;return <Sequence key={t.index} from={t.from} durationInFrames={t.frames}><Comp duration={t.frames}/></Sequence>})}</AbsoluteFill>;
